POST http://192.168.1.96/posts
url: https://jsonplaceholder.typicode.com///
content-type: application/json
accept: application/json

{
    "sad": "culo"
}
###
GET http://192.168.1.63/posts/101
url: https://jsonplaceholder.typicode.com///
###
GET https://jsonplaceholder.typicode.com/posts/10
###
POST https://jsonplaceholder.typicode.com/posts
content-type: application/json
accept: application/json

{
    "title": "dsasadfsad"
}
###